# CMake generated Testfile for 
# Source directory: C:/Users/muham/Desktop/Nexus/lib/NexusData
# Build directory: C:/Users/muham/Desktop/Nexus/lib/NexusData/build-v2
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test_core]=] "C:/Users/muham/Desktop/Nexus/lib/NexusData/build-v2/test_core.exe")
set_tests_properties([=[test_core]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;346;add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;354;nexusdata_add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;0;")
add_test([=[test_ndarray]=] "C:/Users/muham/Desktop/Nexus/lib/NexusData/build-v2/test_ndarray.exe")
set_tests_properties([=[test_ndarray]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;346;add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;355;nexusdata_add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;0;")
add_test([=[test_random]=] "C:/Users/muham/Desktop/Nexus/lib/NexusData/build-v2/test_random.exe")
set_tests_properties([=[test_random]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;346;add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;356;nexusdata_add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;0;")
add_test([=[test_dataset]=] "C:/Users/muham/Desktop/Nexus/lib/NexusData/build-v2/test_dataset.exe")
set_tests_properties([=[test_dataset]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;346;add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;357;nexusdata_add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;0;")
add_test([=[test_dataloader]=] "C:/Users/muham/Desktop/Nexus/lib/NexusData/build-v2/test_dataloader.exe")
set_tests_properties([=[test_dataloader]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;346;add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;358;nexusdata_add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;0;")
add_test([=[test_csv]=] "C:/Users/muham/Desktop/Nexus/lib/NexusData/build-v2/test_csv.exe")
set_tests_properties([=[test_csv]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;346;add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;359;nexusdata_add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;0;")
add_test([=[test_split]=] "C:/Users/muham/Desktop/Nexus/lib/NexusData/build-v2/test_split.exe")
set_tests_properties([=[test_split]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;346;add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;360;nexusdata_add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;0;")
add_test([=[test_transform]=] "C:/Users/muham/Desktop/Nexus/lib/NexusData/build-v2/test_transform.exe")
set_tests_properties([=[test_transform]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;346;add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;361;nexusdata_add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;0;")
add_test([=[test_preprocessing]=] "C:/Users/muham/Desktop/Nexus/lib/NexusData/build-v2/test_preprocessing.exe")
set_tests_properties([=[test_preprocessing]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;346;add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;362;nexusdata_add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;0;")
add_test([=[test_stats]=] "C:/Users/muham/Desktop/Nexus/lib/NexusData/build-v2/test_stats.exe")
set_tests_properties([=[test_stats]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;346;add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;363;nexusdata_add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;0;")
add_test([=[test_image]=] "C:/Users/muham/Desktop/Nexus/lib/NexusData/build-v2/test_image.exe")
set_tests_properties([=[test_image]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;346;add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;364;nexusdata_add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;0;")
add_test([=[test_mnist_cifar]=] "C:/Users/muham/Desktop/Nexus/lib/NexusData/build-v2/test_mnist_cifar.exe")
set_tests_properties([=[test_mnist_cifar]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;346;add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;365;nexusdata_add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;0;")
add_test([=[test_npy]=] "C:/Users/muham/Desktop/Nexus/lib/NexusData/build-v2/test_npy.exe")
set_tests_properties([=[test_npy]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;346;add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;366;nexusdata_add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;0;")
add_test([=[test_perf]=] "C:/Users/muham/Desktop/Nexus/lib/NexusData/build-v2/test_perf.exe")
set_tests_properties([=[test_perf]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;346;add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;367;nexusdata_add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;0;")
add_test([=[test_cuda]=] "C:/Users/muham/Desktop/Nexus/lib/NexusData/build-v2/test_cuda.exe")
set_tests_properties([=[test_cuda]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;346;add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;368;nexusdata_add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;0;")
add_test([=[test_v06]=] "C:/Users/muham/Desktop/Nexus/lib/NexusData/build-v2/test_v06.exe")
set_tests_properties([=[test_v06]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;346;add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;369;nexusdata_add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;0;")
add_test([=[test_hardening]=] "C:/Users/muham/Desktop/Nexus/lib/NexusData/build-v2/test_hardening.exe")
set_tests_properties([=[test_hardening]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;346;add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;370;nexusdata_add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;0;")
add_test([=[test_perf_v08]=] "C:/Users/muham/Desktop/Nexus/lib/NexusData/build-v2/test_perf_v08.exe")
set_tests_properties([=[test_perf_v08]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;346;add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;371;nexusdata_add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;0;")
add_test([=[test_adapters]=] "C:/Users/muham/Desktop/Nexus/lib/NexusData/build-v2/test_adapters.exe")
set_tests_properties([=[test_adapters]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;346;add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;372;nexusdata_add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;0;")
add_test([=[test_simd]=] "C:/Users/muham/Desktop/Nexus/lib/NexusData/build-v2/test_simd.exe")
set_tests_properties([=[test_simd]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;346;add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;374;nexusdata_add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;0;")
add_test([=[test_memory]=] "C:/Users/muham/Desktop/Nexus/lib/NexusData/build-v2/test_memory.exe")
set_tests_properties([=[test_memory]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;346;add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;375;nexusdata_add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;0;")
add_test([=[test_stage_graph]=] "C:/Users/muham/Desktop/Nexus/lib/NexusData/build-v2/test_stage_graph.exe")
set_tests_properties([=[test_stage_graph]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;346;add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;376;nexusdata_add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;0;")
add_test([=[test_fusion]=] "C:/Users/muham/Desktop/Nexus/lib/NexusData/build-v2/test_fusion.exe")
set_tests_properties([=[test_fusion]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;346;add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;377;nexusdata_add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;0;")
add_test([=[test_cost_model]=] "C:/Users/muham/Desktop/Nexus/lib/NexusData/build-v2/test_cost_model.exe")
set_tests_properties([=[test_cost_model]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;346;add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;378;nexusdata_add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;0;")
add_test([=[test_gpu]=] "C:/Users/muham/Desktop/Nexus/lib/NexusData/build-v2/test_gpu.exe")
set_tests_properties([=[test_gpu]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;346;add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;380;nexusdata_add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;0;")
add_test([=[test_sample_fields]=] "C:/Users/muham/Desktop/Nexus/lib/NexusData/build-v2/test_sample_fields.exe")
set_tests_properties([=[test_sample_fields]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;346;add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;383;nexusdata_add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;0;")
add_test([=[test_compression]=] "C:/Users/muham/Desktop/Nexus/lib/NexusData/build-v2/test_compression.exe")
set_tests_properties([=[test_compression]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;346;add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;384;nexusdata_add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;0;")
add_test([=[test_json]=] "C:/Users/muham/Desktop/Nexus/lib/NexusData/build-v2/test_json.exe")
set_tests_properties([=[test_json]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;346;add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;385;nexusdata_add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;0;")
add_test([=[test_arrow]=] "C:/Users/muham/Desktop/Nexus/lib/NexusData/build-v2/test_arrow.exe")
set_tests_properties([=[test_arrow]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;346;add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;386;nexusdata_add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;0;")
add_test([=[test_phase3_io]=] "C:/Users/muham/Desktop/Nexus/lib/NexusData/build-v2/test_phase3_io.exe")
set_tests_properties([=[test_phase3_io]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;346;add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;387;nexusdata_add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;0;")
add_test([=[test_phase4]=] "C:/Users/muham/Desktop/Nexus/lib/NexusData/build-v2/test_phase4.exe")
set_tests_properties([=[test_phase4]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;346;add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;388;nexusdata_add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;0;")
add_test([=[test_phase6]=] "C:/Users/muham/Desktop/Nexus/lib/NexusData/build-v2/test_phase6.exe")
set_tests_properties([=[test_phase6]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;346;add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;389;nexusdata_add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;0;")
add_test([=[test_extensibility]=] "C:/Users/muham/Desktop/Nexus/lib/NexusData/build-v2/test_extensibility.exe")
set_tests_properties([=[test_extensibility]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;346;add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;390;nexusdata_add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;0;")
add_test([=[fuzz_smoke]=] "C:/Users/muham/Desktop/Nexus/lib/NexusData/build-v2/fuzz_smoke.exe")
set_tests_properties([=[fuzz_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;433;add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;0;")
add_test([=[install_find_package_smoke]=] "C:/Program Files/JetBrains/CLion 2026.2.1/bin/cmake/win/x64/bin/cmake.exe" "-DNexusData_SOURCE_DIR=C:/Users/muham/Desktop/Nexus/lib/NexusData" "-DNexusData_BINARY_DIR=C:/Users/muham/Desktop/Nexus/lib/NexusData/build-v2" "-DNexusData_GENERATOR=Ninja" "-DNexusData_CXX_COMPILER=C:/Program Files/JetBrains/CLion 2026.2.1/bin/mingw/bin/c++.exe" "-DNexusData_BUILD_TYPE=Release" "-DNexusData_ARROW_PREFIX=" "-P" "C:/Users/muham/Desktop/Nexus/lib/NexusData/cmake/install_smoke.cmake")
set_tests_properties([=[install_find_package_smoke]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;522;add_test;C:/Users/muham/Desktop/Nexus/lib/NexusData/CMakeLists.txt;0;")
subdirs("_deps/nd_xz-build")
subdirs("_deps/doctest-build")
