#pragma once

/// Umbrella header for NexusData v1.0 public API.

#include "nexusdata/version.hpp"
#include "nexusdata/core/allocator.hpp"
#include "nexusdata/core/arena_allocator.hpp"
#include "nexusdata/core/array_utils.hpp"
#include "nexusdata/core/object_pool.hpp"
#include "nexusdata/core/dtype.hpp"
#include "nexusdata/core/error.hpp"
#include "nexusdata/core/ndarray.hpp"
#include "nexusdata/core/random.hpp"
#include "nexusdata/core/shape.hpp"

#include "nexusdata/backend/backend.hpp"
#include "nexusdata/backend/bounded_queue.hpp"
#include "nexusdata/backend/cost_model.hpp"
#include "nexusdata/backend/gpu_executor.hpp"
#include "nexusdata/backend/gpu_telemetry.hpp"
#include "nexusdata/backend/kernels.hpp"
#include "nexusdata/image/nvjpeg.hpp"
#include "nexusdata/pipeline/augment.hpp"
#include "nexusdata/backend/cpu_dispatch.hpp"
#include "nexusdata/backend/cuda_api.hpp"
#include "nexusdata/backend/device.hpp"
#include "nexusdata/backend/philox.hpp"
#include "nexusdata/backend/pinned.hpp"
#include "nexusdata/backend/thread_pool.hpp"

#include "nexusdata/adapter/dlpack.hpp"
#include "nexusdata/adapter/matrixflash.hpp"

#include "nexusdata/bench/harness.hpp"

#include "nexusdata/cache/disk_cache.hpp"
#include "nexusdata/cache/lru_cache.hpp"

#include "nexusdata/dataset/audio.hpp"
#include "nexusdata/dataset/cached.hpp"
#include "nexusdata/dataset/cifar.hpp"
#include "nexusdata/dataset/compose.hpp"
#include "nexusdata/dataset/csv/csv_dataset.hpp"
#include "nexusdata/dataset/dataset.hpp"
#include "nexusdata/dataset/hdf5.hpp"
#include "nexusdata/dataset/image_folder.hpp"
#include "nexusdata/dataset/in_memory.hpp"
#include "nexusdata/dataset/iterable.hpp"
#include "nexusdata/dataset/jsonl.hpp"
#include "nexusdata/dataset/map.hpp"
#include "nexusdata/dataset/mnist.hpp"
#include "nexusdata/dataset/npy.hpp"
#include "nexusdata/dataset/parquet.hpp"
#include "nexusdata/dataset/sample.hpp"
#include "nexusdata/dataset/split.hpp"
#include "nexusdata/dataset/sqlite.hpp"
#include "nexusdata/dataset/stats.hpp"
#include "nexusdata/dataset/subset.hpp"
#include "nexusdata/dataset/text.hpp"
#include "nexusdata/dataset/webdataset.hpp"

#include "nexusdata/fuzz/harness.hpp"

#include "nexusdata/image/image.hpp"
#include "nexusdata/io/mapped_file.hpp"

#include "nexusdata/loading/batch.hpp"
#include "nexusdata/loading/dataloader.hpp"

#include "nexusdata/pipeline/fusion.hpp"
#include "nexusdata/pipeline/image.hpp"
#include "nexusdata/pipeline/persist.hpp"
#include "nexusdata/pipeline/stage_graph.hpp"
#include "nexusdata/pipeline/tabular.hpp"
#include "nexusdata/pipeline/transform.hpp"

#include "nexusdata/preprocessing/encoder.hpp"
#include "nexusdata/preprocessing/imputer.hpp"
#include "nexusdata/preprocessing/scaler.hpp"
#include "nexusdata/preprocessing/transformer.hpp"

#include "nexusdata/sampling/advanced.hpp"
#include "nexusdata/sampling/random.hpp"
#include "nexusdata/sampling/sampler.hpp"
#include "nexusdata/sampling/sequential.hpp"

#include "nexusdata/simd/byte_scan.hpp"
#include "nexusdata/simd/image_ops.hpp"
#include "nexusdata/simd/numeric_ops.hpp"
